apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: c05t0m3my-nodejs 
  janus-idp.io/tekton: c05t0m3my-nodejs
  backstage.io/kubernetes-id: c05t0m3my-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c05t0m3my-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  