apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c05t0m3my-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c05t0m3my-nodejs 
  name: c05t0m3my-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: c05t0m3my-nodejs 
